default: &default
  db: 1
  url: redis://localhost:6379

development:
  <<: *default
test:
  <<: *default
production:
  <<: *default
  url: <%= ENV["REDIS_URL"] %>
  host: <%= ENV["REDISHOST"] %>
  password: <%= ENV["REDISPASSWORD"] %>
  port: <%= ENV["REDISPORT"] %>
  user: <%= ENV["REDISUSER"] %>
  